-- oracle_rewards_schema.sql
-- Connect as LEVELUP user before executing or include CONNECT LEVELUP/levelup123;

CREATE TABLE users (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name VARCHAR2(200),
  email VARCHAR2(200),
  points NUMBER DEFAULT 0
);

CREATE TABLE rewards (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  title VARCHAR2(200),
  cost_points NUMBER,
  description CLOB
);